version: '3'

services:
  stock-api:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    restart: unless-stopped
    environment:
      - TZ=Asia/Ho_Chi_Minh
      - FRONTEND_URL=http://localhost:3000,https://vlb-vanlang-budget.vercel.app
